### PR TITLE
Add links to SCIM Group SRAM Extension block

### PR DESCRIPTION
**Pull request by HarryKodden**
#1239

### CODE REVIEW

**Comment by mrvanes** [comment]
In ldap `labeledURI` points to the `sbs_url` (`https://sbs.scz-vm.net/collaborations/da706611-0afb-4a7a-819b-b0a9c63e9b67 sbs_url`) but in the SCIM implementation it points to the user defined website (`https://www.google.nl`). Which one should it be?

**Comment by baszoetekouw** [comment]
Should be the same as ldap, so link to the CO page.
@HarryKodden can you fix that?

**Comment by baszoetekouw** [comment]
So to be explicit: instead of the "Website URL" as entered in the CO details screen, we want to put the `sbs_uri` in the SCIM output, as defined here for LDAP: https://github.com/SURFscz/SBS/blob/main/server/api/plsc.py#L68-L73

Also, please also rename it to `sbs_url` to make it consistent with ldap

**Comment by HarryKodden** [comment]
PR submitted
https://github.com/SURFscz/SBS/pull/1537

**Comment by baszoetekouw** [comment]
works, but see #1539

**Pull request merged**
